apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: consul-k8s-0
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "managed-nfs-storage"
    nfs:
      path: /k8s/data/consul/0
      server: 2.2.2.25

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: consul-k8s-1
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "managed-nfs-storage"
    nfs:
      path: /k8s/data/consul/1
      server: 2.2.2.25

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: consul-k8s-2
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "managed-nfs-storage"
    nfs:
      path: /k8s/data/consul/2
      server: 2.2.2.25

- apiVersion: v1
  kind: Service
  metadata:
    name: consul-svc
    namespace: monitoring
    labels:
      name: consul
  spec:
    type: ClusterIP
    selector:
     app: consul
    ports:
     - name: http
       port: 8500
     - name: https
       port: 8443
     - name: rpc
       port: 8400
     - name: serflan-tcp 
       protocol: "TCP"
       port: 8301
     - name: serflan-udp
       protocol: "UDP"
       port: 8301
     - name: serfwan-tcp
       protocol: "TCP"
       port: 8302
     - name: serfwan-udp
       protocol: "UDP"
       port: 8302
     - name: server
       port: 8300
     - name: consuldns
       port: 8600
    

- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: consul
    namespace: monitoring
  spec:
    serviceName: consul-svc
    replicas: 3
    template:
      metadata:
        labels:
          app: consul
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values: 
                      - consul
                topologyKey: "kubernetes.io/hostname"
        terminationGracePeriodSeconds: 30
        containers:
        - name: consul
          image: dockerhub.azk8s.cn/library/consul:1.5.3
          args:
            - "agent"
            - "-server"
            - "-bootstrap-expect=3"
            - "-ui"
            - "-data-dir=/consul/data"
            - "-bind=0.0.0.0"
            - "-client=0.0.0.0"
            - "-advertise=$(PODIP)"
            - "-retry-join=consul-0.consul-svc"
            - "-retry-join=consul-1.consul-svc"
            - "-retry-join=consul-2.consul-svc"
            - "-domain=cluster.local"
            - "-disable-host-node-id"
          env:
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
          - containerPort: 8500
            name: ui-port
          - containerPort: 8400
            name: alt-port
          - containerPort: 53
            name: udp-port
          - containerPort: 8443
            name: https-port
          - containerPort: 8080
            name: http-port
          - containerPort: 8301
            name: serflan
          - containerPort: 8302
            name: serfwan
          - containerPort: 8600
            name: consuldns
          - containerPort: 8300
            name: server
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          volumeMounts:
          - name: consul-data
            mountPath: /consul/data
    volumeClaimTemplates:
    - metadata:
        name: consul-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: "managed-nfs-storage"
        resources:
          requests:
            storage: 5Gi